spring:
  profiles:
    active: local
    include:
      - db
      - auth

naver:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region-name: kr-standard
    bucket-name: hook-killer-file-bucket



auth:
  jwt:
    header: "Authorization"
    prefix: "Bearer "
    secret-key: hokasdofkoasdkfoafjasdlkfjsadlkfjeijflasdkfjasdfasdfasdfaefargagstrghehasdfasfaegargasfsadfdaga
    access-exp: 36000
    refresh-exp: 3600
    issuer: hookkiller